### ISSUE TITLE
Boot time: roadmap 

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#125]
- [ ] watchBootKernel: procedure to observe whether the kernel boots and how many times it takes
- [ ] any configuration as input

**Comment by FAMILIAR-project** [comment]
So far, we've tried something like:
```
make O=$TOP/build/linux-x86-basic x86_64_defconfig
make O=$TOP/build/linux-x86-basic kvmconfig
```

basically it uses a pre-defined configuration `x86_64_defconfig` and "complement" it with kvmconfig 
https://github.com/torvalds/linux/blob/master/kernel/configs/kvm_guest.config
https://github.com/torvalds/linux/blob/master/scripts/kconfig/Makefile#L99-L101 

What we really want is to compile **any** configuration (not only x86_64_defconfig)  and check its boot-ability. 

A naive solution would be something like 
`make O=$TOP/build/linux-x86-basic randconfig`

**important note:** we want x86_64 support, not x86_32
Problem: it seems not working at all with QEMU (the process is blocking) and a basic explanation is that there are not specific options of kvmconfig.

Another attempt is 
```
make O=$TOP/build/linux-x86-basic randconfig 
make O=$TOP/build/linux-x86-basic kvmconfig
```
but my experiences show that it drastically changes the original random configuration, overriding some options in a strange way. 

Overall, the proper way might be something like
 ```
 KCONFIG_ALLCONFIG=qemu64.config make O=$TOP/build/linux-x86-basic randconfig 
```

where:
qemu64.config is an accessible file that contains options of https://github.com/torvalds/linux/blob/master/kernel/configs/kvm_guest.config (note: kvm_guest.config has evolved and is of course different for version 4.13.3) + CONFIG_64BIT=y 

something like: 
```
CONFIG_64BIT=y
CONFIG_NET=y
CONFIG_NET_CORE=y
CONFIG_NETDEVICES=y
CONFIG_BLOCK=y
CONFIG_BLK_DEV=y
CONFIG_NETWORK_FILESYSTEMS=y
CONFIG_INET=y
CONFIG_TTY=y
CONFIG_SERIAL_8250=y
CONFIG_SERIAL_8250_CONSOLE=y
CONFIG_IP_PNP=y
CONFIG_IP_PNP_DHCP=y
CONFIG_BINFMT_ELF=y
CONFIG_PCI=y
CONFIG_PCI_MSI=y
CONFIG_DEBUG_KERNEL=y
CONFIG_VIRTUALIZATION=y
CONFIG_HYPERVISOR_GUEST=y
CONFIG_PARAVIRT=y
CONFIG_KVM_GUEST=y
CONFIG_VIRTIO=y
CONFIG_VIRTIO_PCI=y
CONFIG_VIRTIO_BLK=y
CONFIG_VIRTIO_CONSOLE=y
CONFIG_VIRTIO_NET=y
CONFIG_9P_FS=y
CONFIG_NET_9P=y
CONFIG_NET_9P_VIRTIO=y
CONFIG_SCSI_LOWLEVEL=y
CONFIG_SCSI_VIRTIO=y
CONFIG_VIRTIO_INPUT=y
CONFIG_DRM_VIRTIO_GPU=y
```

because it will pre-set options for QEMU **before** randomly choosing the rest of options values. 
We have to try! 

@JulienRC @psaffray @ernael can you try and report on the results? 

A possible roadmap: 

- [x] compile a random configuration (as documented here) and test its bootability with QEMU
- [ ] build automatically the file qemu64.config in the right place by concatenating the content of kvm_guest.config with CONFIG_64BIT=y
- [ ] modify scriptBootKernel.sh to integrate our solution 
- [ ] investigate/explain what KVM options are really needed

**Comment by FAMILIAR-project** [comment]
duplicates with other issues
